plugins {
    id 'java-library'
    id 'maven-publish'
}

base { archivesName = "${mod_id}-${project.name}-${minecraft_version}" }
java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach { options.release = java_version as int }

tasks.withType(Jar).configureEach {
    from(rootProject.file('LICENSE')) { rename { "${it}_${mod_name}" } }
}

processResources {
    def props = [
        version: version,
        group: project.group,
        minecraft_version: minecraft_version,
        minecraft_version_range: minecraft_version_range,
        fabric_version: fabric_version,
        fabric_loader_version: fabric_loader_version,
        mod_name: mod_name,
        mod_author: mod_author,
        mod_id: mod_id,
        license: license,
        description: providers.gradleProperty('description').get(),
        neoforge_version: neoforge_version,
        neoforge_loader_version_range: neoforge_loader_version_range,
        credits: credits,
        java_version: java_version
    ]
    def jsonProps = props.collectEntries { k, v -> [(k): v instanceof String ? v.replace('\n', '\\\\n') : v] }
    filesMatching(['META-INF/mods.toml']) { expand props }
    filesMatching(['pack.mcmeta', 'fabric.mod.json', '*.mixins.json']) { expand jsonProps }
    inputs.properties(props)
}
